# -*- coding: utf-8 -*-
"""Impact of ai model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Se4AbwfJPFzRY2BVTkPFK1sK01D0Y7-R

#**The Impact of AI on Students**

##**Gernral look**

###Import the nessary libaraies
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""###*Read the data*"""

ID = "1bN331ALpiIp_pSG_-WFq1Ga7dvOlKSr7"
url = f"https://drive.google.com/uc?export=download&id={ID}"

df = pd.read_csv(url)
df.head()

"""###Insites about the data"""

df = df.drop(columns="Student_ID")
df.head()

df.info()

df.describe()

df.describe(include="object")

objects = df.select_dtypes("object").columns
for o in objects:

  print(df[o].value_counts())
  print()

"""* Adding a column for the the difference between pre and post semester gpa"""

df["GPA_Delta"] = df["Post_Semester_GPA"] - df["Pre_Semester_GPA"]
sns.set_theme(style="whitegrid")
df.head()

"""###Observe Outlayers"""

nums= df.select_dtypes("number").columns
for col in nums:
  plt.boxplot(df[col])
  plt.title(col)
  plt.show()

for col in nums:
  plt.hist(df[col],bins = 30)
  plt.title(col)
  plt.show()

"""#Visulization"""

# sns.pairplot(data=df)
# plt.show()

gpas = ["Pre_Semester_GPA","Post_Semester_GPA","GPA_Delta"]
numeric_ai_usage = ["Weekly_GenAI_Hours","Tool_Diversity"]
numeric_study_behavior = ["Traditional_Study_Hours","Perceived_AI_Dependency"]

sns.countplot(data=df, x='Burnout_Risk_Level', order=['Low', 'Medium', 'High'])
plt.title('Target Class Distribution: Burnout Risk Level')
plt.show()

"""* there is a lit difference between the burnout levels"""

features = ['Anxiety_Level_During_Exams', 'Perceived_AI_Dependency', 'Weekly_GenAI_Hours',"Traditional_Study_Hours"]
for feature in features:
  col = df[feature]
  plt.boxplot([col[df["Burnout_Risk_Level"]=="Low"],col[df["Burnout_Risk_Level"]=="Medium"],col[df["Burnout_Risk_Level"]=="High"]],tick_labels=["Low","Medium","High"])
  plt.title(f"{feature} X Burnout Risk Level")
  plt.ylabel(feature)
  plt.xlabel('Burnout Risk Level')
  plt.show()

"""the relationship between burnout risk level and:
  * Anxity level during exams & percived AI Dependency & weekly gen AI hours is positive
  * while with traditional study hours is negative
"""

# 1. Calculate percentage cross-tabulation
ct = (
    pd.crosstab(
        df['Major_Category'], df['Burnout_Risk_Level'], normalize='index'
    )[['Low', 'Medium', 'High']]
    * 100
)

# 2. Plot stacked bar chart directly
ax = ct.plot(kind='bar', stacked=True, figsize=(9, 5), rot=0)

# 3. Add percentage labels using fmt string
for container in ax.containers:
  ax.bar_label(
      container,
      fmt='%.2f%%',
      label_type='center',
      fontsize=9,
      fontweight='bold',
      color='white',
  )

plt.title('Proportion of Burnout Risk Levels Across Major Categories')
plt.ylabel('Percentage (%)')
plt.legend(title='Burnout Risk', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.show()

"""* STM  major has the highest high burnout risks"""

cats = ['Institutional_Policy', 'Prompt_Engineering_Skill', 'Primary_Use_Case', 'Major_Category']
fig, axes = plt.subplots(2, 2, figsize=(18, 14))

for col, ax in zip(cats, axes.flatten()):
    # Calculate row-wise proportions (%)
    ct = pd.crosstab(df[col], df['Burnout_Risk_Level'], normalize='index')[['Low', 'Medium', 'High']] * 100

    # Plot stacked bar chart
    ct.plot(kind='bar', stacked=True, ax=ax, colormap='coolwarm', legend=(ax == axes[0, 0]))

    # Write percentage values inside each box
    for c in ax.containers:
        # Option A: Standard formatting for all boxes
        # ax.bar_label(c, fmt='%.1f%%', label_type='center', fontsize=9, fontweight='bold')

        # Option B: Clean formatting (hides percentage if segment is smaller than 2% to prevent overlap)
        labels = [f'{height:.1f}%' if (height := rect.get_height()) >= 2 else '' for rect in c]
        ax.bar_label(c, labels=labels, label_type='center', fontsize=9, fontweight='bold', color='black')

    ax.set_title(f'Burnout Risk Density by {col}', fontsize=12, fontweight='bold')
    ax.set_ylabel('Percentage (%)')
    ax.set_xlabel('')
    ax.set_ylim(0, 105)  # Keeps bars nicely within bounds
    ax.tick_params(axis='x', rotation=30)

plt.tight_layout()
plt.show()

# Melt dataset to compare both hour types side-by-side
hours_df = df.melt(
    id_vars=['Burnout_Risk_Level', 'Prompt_Engineering_Skill'],
    value_vars=['Weekly_GenAI_Hours', 'Traditional_Study_Hours'],
    var_name='Study_Type',
    value_name='Hours'
)

sns.catplot(
    data=hours_df,
    x='Prompt_Engineering_Skill',
    y='Hours',
    hue='Study_Type',
    col='Burnout_Risk_Level',
    col_order=['Low', 'Medium', 'High'],
    kind='box',

)
plt.subplots_adjust(top=0.85)
plt.suptitle('Weekly Hours Allocation (AI vs Traditional) across Prompt Skill & Burnout')
plt.show()

plt.figure(figsize=(11, 6))
sns.boxplot(
    data=df,
    x='Institutional_Policy',
    y='Anxiety_Level_During_Exams',
    hue='Burnout_Risk_Level',
    hue_order=['Low', 'Medium', 'High'],
)
plt.title('Exam Anxiety Levels by Institutional Policy & Burnout Tier')
plt.xlabel('Institutional Policy')
plt.ylabel('Exam Anxiety (1 - 10)')
plt.legend(title='Burnout Risk')
plt.show()

"""* Then strictly baning AI usage raises Anxiety levels during exames"""

sns.lineplot(
    data=df,
    x='Anxiety_Level_During_Exams',
    y='Post_Semester_GPA',
    hue='Institutional_Policy',
    marker='o',
    linewidth=2.5,
    errorbar=None
)
plt.title('Mean Post-Semester GPA across Anxiety Levels (1-10) by Policy', fontsize=12, fontweight='bold')
plt.xlabel('Exam Anxiety Level (1 = Low, 10 = Severe)')
plt.ylabel('Mean Post-Semester GPA')
plt.xticks(range(1, 11))
plt.show()

"""* Even when students say that they have a high level of anxity duing the exame , their result differes and the more strict the policy get the more badly the perform at high anxity levels"""

numerical_data=df.select_dtypes(include="number").columns
numerical_data

df["Perceived_AI_Dependency"].value_counts()

# outlier_data=["Pre_Semester_GPA","Weekly_GenAI_Hours","Traditional_Study_Hours","Post_Semester_GPA"]
for i in numerical_data:
  Q1 = df[i].quantile(0.25)
  Q3 = df[i].quantile(0.75)
  IQR = Q3 - Q1

  lower_bound = max(0, Q1 - 1.5 * IQR)
  upper_bound = Q3 + 1.5 * IQR
  df = df[(df[i] >= lower_bound) & (df[i] <= upper_bound)]
  print(i)
  print(upper_bound,lower_bound)

df = pd.get_dummies(df,columns=["Major_Category" , "Primary_Use_Case" ])
df.head()

for col in df.select_dtypes("object").columns:
  print(col)
  print(df[col].value_counts())
  print()

cats = df.select_dtypes(include=['object', 'bool', 'category']).columns
nums = df.select_dtypes(include=['int64', 'float64']).columns
print(cats)
print(nums)

class_cats = cats.drop("Burnout_Risk_Level")
class_nums = nums

reg_cats = cats
reg_nums = nums.drop(["GPA_Delta","Post_Semester_GPA"])
 # category and binary cols

general_map = {
"Year_of_Study" : {
    'Freshman': 1,
    'Sophomore': 2,
    'Junior': 3,
    'Senior': 4,
    'Graduate': 5
} ,

"Prompt_Engineering_Skill" : {
    'Beginner': 1,
    'Intermediate': 2,
    'Advanced': 3
} ,

"Institutional_Policy" : {
    'Strict_Ban': 1,
    'Allowed_With_Citation': 2,
    'Actively_Encouraged': 3
} ,

"Burnout_Risk_Level" : {
    'Low': 1,
    'Medium': 2,
    'High': 3
}
}
df['Year_of_Study'] = df['Year_of_Study'].map(general_map["Year_of_Study"])
df['Prompt_Engineering_Skill'] = df['Prompt_Engineering_Skill'].map(general_map["Prompt_Engineering_Skill"])
df['Institutional_Policy'] = df['Institutional_Policy'].map(general_map["Institutional_Policy"])
df['Burnout_Risk_Level'] = df['Burnout_Risk_Level'].map(general_map["Burnout_Risk_Level"])



df.head()

"""# splitting and scaling the model"""

from sklearn.model_selection import train_test_split
class_x = df.drop(columns="Burnout_Risk_Level")
class_y = df["Burnout_Risk_Level"]

class_bool_cols = class_x.select_dtypes(include="bool").columns

class_cols_order = class_x.columns

x_train, x_test, y_train, y_test = train_test_split(class_x, class_y, test_size=0.3, random_state = 58)

print(class_nums)
print(class_cats)
print(class_cols_order)

from sklearn.preprocessing import StandardScaler


# 1. Instantiate once
class_scaler = StandardScaler()

# 2. Fit and transform training data on 'scaler'
x_train[numerical_data] = class_scaler.fit_transform(x_train[numerical_data])

# 3. Transform test data using the SAME 'scaler' instance
x_test[numerical_data] = class_scaler.transform(x_test[numerical_data])

x_train.head()

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.naive_bayes import BernoulliNB
from sklearn.ensemble import AdaBoostClassifier , RandomForestClassifier

class_models={"LR": LogisticRegression(max_iter=1000),"Tree":DecisionTreeClassifier(),"RF":RandomForestClassifier(),"KNN":KNeighborsClassifier(),'ADABOOST':AdaBoostClassifier()}

for name ,model in class_models.items():
    model.fit(x_train,y_train)
    y_pre_train = model.predict(x_train)
    y_pre_test = model.predict(x_test)
    print(name)
    print(classification_report(y_train,y_pre_train))
    print(classification_report(y_test,y_pre_test))
    print("------------------------------------------------")

"""##New Target "Post_Semester_GPA"
"""

reg_x = df.drop(columns={"Post_Semester_GPA","GPA_Delta"})
reg_y = df["Post_Semester_GPA"]

reg_bool_cols = reg_x.select_dtypes(include="bool").columns
reg_cols_order = reg_x.columns

x_train, x_test, y_train, y_test = train_test_split(reg_x, reg_y, test_size=0.3, random_state = 58)

reg_numerical_data = numerical_data.drop(["Post_Semester_GPA","GPA_Delta"])
# 1. Instantiate once
reg_scaler =StandardScaler()

# 2. Fit and transform training data on 'scaler'
x_train[reg_numerical_data] = reg_scaler.fit_transform(x_train[reg_numerical_data])

# 3. Transform test data using the SAME 'scaler' instance
x_test[reg_numerical_data] = reg_scaler.transform(x_test[reg_numerical_data])

x_train.head()

from sklearn.ensemble import AdaBoostRegressor, RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

Regression_models = {
    'LR': LinearRegression(),
    'Tree': DecisionTreeRegressor(random_state=42),
    'RF': RandomForestRegressor(random_state=42),
    'KNN': KNeighborsRegressor(),
    'ADABOOST': AdaBoostRegressor(random_state=42),
}

for name, model in Regression_models.items():
  model.fit(x_train, y_train)

  y_pred_train = model.predict(x_train)
  y_pred_test = model.predict(x_test)

  print(f'================ {name} ================')

  # Train metrics
  train_r2 = r2_score(y_train, y_pred_train)
  train_rmse = np.sqrt(mean_squared_error(y_train, y_pred_train))
  train_mae = mean_absolute_error(y_train, y_pred_train)

  # Test metrics
  test_r2 = r2_score(y_test, y_pred_test)
  test_rmse = np.sqrt(mean_squared_error(y_test, y_pred_test))
  test_mae = mean_absolute_error(y_test, y_pred_test)

  print(
      f'TRAIN -> R2: {train_r2:.4f} | RMSE: {train_rmse:.4f} | MAE:'
      f' {train_mae:.4f}'
  )
  print(
      f'TEST  -> R2: {test_r2:.4f} | RMSE: {test_rmse:.4f} | MAE:'
      f' {test_mae:.4f}'
  )
  print('------------------------------------------------\n')

"""#Downloading The models"""

import pickle

with open('classification_model.pkl', 'wb') as f:
    pickle.dump({
        "model": class_models["LR"],
        'scaler': class_scaler,
        'scaled_cols': numerical_data,
        'label_encoder': general_map,
        'bool_cols': class_bool_cols,
        'numeric_cols': class_nums,
        'binary_cols': class_cats,
        'feature_order': class_cols_order
    }, f)

# Combine numerical_data and general_map keys into a set
existing_features = set(numerical_data).union(general_map.keys(),class_bool_cols)


for i in class_cols_order:
    if i not in existing_features:
        print(i)

with open('Regression_model.pkl', 'wb') as f:
    pickle.dump({
        "model": Regression_models["RF"],
        'scaler': reg_scaler,
        'scaled_cols': reg_numerical_data,
        'label_encoder': general_map,
        'bool_cols': reg_bool_cols ,
        'numeric_cols': reg_nums,
        'binary_cols': reg_cats,
        'feature_order': reg_cols_order
    }, f)

existing_features = set(reg_numerical_data).union(general_map.keys(),reg_bool_cols)

for i in reg_cols_order:
    if i not in existing_features:
        print(i)

